name: Release new rehashes version

on:
  release:
    types: [published]

jobs:
  release_artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success
      - name: Collect into dist
        run: |
          mkdir dist
          find . -type f \( -name "*.whl" -o -name "*.tar.gz" \) \
            -exec cp {} dist/ \;
          ls -lah dist
      - uses: nanoufo/action-upload-artifacts-and-release-assets@v2
        with:
          path: |
            dist/*.whl
            dist/*.tar.gz
          upload-release-files: true
          release-upload-url: ${{ github.event.release.upload_url }}
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages-dir: dist/
